export const cfbGroupIdMapping = new Map([
  ["-1", "Top 25"],
  ["80", "FBS"],
  ["8", "SEC"],
  ["5", "Big Ten"],
  ["4", "Big 12"],
  ["1", "ACC"],
  ["15", "MAC"],
  ["151", "American Athletic Conference"],
  ["12", "CUSA"],
  ["18", "FBS Independents"],
  ["17", "Mountain West"],
  ["9", "Pac 12"],
  ["37", "Sun Belt"],
  ["81", "FCS"],
  ["28", "Big Sky"],
  ["48", "CAA"],
  ["32", "FC Independents"],
  ["22", "Ivy"],
  ["24", "MEAC"],
  ["21", "MVFC"],
  ["25", "NEC"],
  ["179", "OVC-Big South"],
  ["27", "Patriot"],
  ["28", "Pioneer"],
  ["29", "Southern"],
  ["30", "Southland"],
  ["31", "SWAC"],
  ["177", "UAC"],
  ["35", "Div II/III"],
]);

export const defaultCfbGroupId = "-1";

export const cfbWeeksList = [
  "Week 1",
  "Week 2",
  "Week 3",
  "Week 4",
  "Week 5",
  "Week 6",
  "Week 7",
  "Week 8",
  "Week 9",
  "Week 10",
  "Week 11",
  "Week 12",
  "Week 13",
  "Week 14",
  "Week 15",
  "Week 16",
  "Bowls",
  "CFP",
];

export const cfbWeeksMap = new Map([
  ["Week 1", "1"],
  ["Week 2", "2"],
  ["Week 3", "3"],
  ["Week 4", "4"],
  ["Week 5", "5"],
  ["Week 6", "6"],
  ["Week 7", "7"],
  ["Week 8", "8"],
  ["Week 9", "9"],
  ["Week 10", "10"],
  ["Week 11", "11"],
  ["Week 12", "12"],
  ["Week 13", "13"],
  ["Week 14", "14"],
  ["Week 15", "15"],
  ["Week 16", "16"],
  ["Bowls", "BOWLS-1"],
  ["CFP", "CFP-999"],
]);
