export const cfbGroupIdMapping = new Map([
  ["-1", "Top 25"],
  ["80", "FBS"],
  ["8", "SEC"],
  ["5", "Big Ten"],
  ["4", "Big 12"],
  ["1", "ACC"],
  ["15", "MAC"],
  ["151", "American Athletic Conference"],
  ["12", "CUSA"],
  ["18", "FBS Independents"],
  ["17", "Mountain West"],
  ["9", "Pac 12"],
  ["37", "Sun Belt"],
  ["81", "FCS"],
  ["28", "Big Sky"],
  ["48", "CAA"],
  ["32", "FC Independents"],
  ["22", "Ivy"],
  ["24", "MEAC"],
  ["21", "MVFC"],
  ["25", "NEC"],
  ["179", "OVC-Big South"],
  ["27", "Patriot"],
  ["28", "Pioneer"],
  ["29", "Southern"],
  ["30", "Southland"],
  ["31", "SWAC"],
  ["177", "UAC"],
  ["35", "Div II/III"],
]);

export const defaultCfbGroupId = "-1";
