type Game = {
  id: string;
  homeTeam: string;
  homeTeamId: string;
  awayTeamId: string;
  homeTeamLogo: string;
  awayTeam: string;
  awayTeamLogo: string;
  location: string;
  homeScore: string;
  awayScore: string;
  period: string;
  channel: string;
  espnLink: string;
  lastPlay: string;
  currentDownAndDistance: string;
  possessionTeamId: string;
  homeTeamRecord: string;
  awayTeamRecord: string;
};
